database:
  db_url: "postgres://test:123456@0.0.0.0:5433/popcity"
  max_connect_pool: 30
  min_connect_pool: 10
  connect_timeout: 30
  acquire_timeout: 60
server:
  host: "0.0.0.0"
  port: "8080"
auth:
  client_id: ""
  client_secret: ""
  redirect_url: "http://127.0.0.1:8080/auth/callback"
redis:
  redis_url: "redis://:@127.0.0.1:6379/"
