[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1.1", features = ["sqlx-postgres", "runtime-async-std" , "runtime-tokio"] }
sea-orm-migration = "1.1.1"
